server:
  shutdown: graceful
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel.enabled: false

spring:
  config:
    import:
      - application-mysql.yml
  profiles:
    group:
      default: local
  lifecycle:
    timeout-per-shutdown-phase: 20s


springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs

logging:
  level:
    rsupport.test: debug
    org.hibernate.type.descriptor.sql: trace


