spring:
  config:
    import:
      - application-common.yml
      - application-mysql.yml
      - application-redis.yml
      - application-springdoc.yml
  profiles:
    group:
      default: local
      sandbox: sandbox





