spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1q2w3e4r!
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
---
spring:
  config.activate.on-profile: local


---
spring:
  config.activate.on-profile: sandbox
