springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
---
spring:
  config.activate.on-profile: local
springdoc.swagger-ui.enabled: true

---
spring:
  config.activate.on-profile: prod

springdoc.swagger-ui.enabled: false