spring:
  config:
    import:
      - application-mysql.yml
  profiles:
    group:
      default: local

springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs

logging:
  level:
    rsupport.test: debug
    org.hibernate.type.descriptor.sql: trace


