server:
  shutdown: graceful
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel.enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  lifecycle.timeout-per-shutdown-phase: 20s

storage:
  path: /var/tmp/rsupport
  allow-file-extension: jpg, jpeg, png, xls, xlsx, doc, docx, ppt, pptx, hwp, hwpx, pdf
  allow-mime-type:
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.openxmlformats-officedocument.presentationml.presentation
    - application/vnd.ms-powerpoint
    - application/msword
    - application/pdf
    - image/jpeg
    - image/x-citrix-jpeg
    - image/pjpeg
    - image/png
    - image/x-citrix-png
    - image/x-png
    - application/vnd.hancom.hwp
    - application/haansofthwp
    - application/x-hwp
    - application/vnd.hancom.hwpx
    - application/haansofthwpx

jwt:
  access-token-expires-in: 1800000 # 30min (1000L * 60 * 30)
  refresh-token-expires-in: 604800000 # 7day (1000L * 60 * 60 * 24 * 7)
  secret: Fr2OrGWctOX4vRp4/osmk6uedZ+/7HQuXqXhsVcskg3Yo0r3U0q2sp/0BzLHPc5ZUxwSm9LQzedsmOlatir05N+h2xxhCPPlbZ8M+dY2Ui4OUhTdgLt3E2EeyRbmA2/DGQqZXAlT5pPay/er9GpiVJ9J66x/Nmlsw8SgUVxEkd9Vrvzowi7O5sns9vI1d71dU7tQuUnP+HZHkZbIjLXengpj7we7DGZqT511ckhciLX+ByFMYn6S2CxfGmGjsldoyL/8Jr+zYgNEReOkMrZWWTno1tJa3ghcVzSzbBZS8/Vi1BY+3sEnikunpscsC+Q35PjnGCs38UHsinjViUDcZQ==


---
spring:
  config.activate.on-profile: local
  docker:
    compose:
      file: ./env/mysql/mysql-compose.yml
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: stop
        timeout: 1m
      skip:
        in-tests: false

logging:
  level:
    rsupport.test: debug
    org.hibernate.type.descriptor.sql: trace

---
spring:
  config.activate.on-profile: sandbox
logging:
  level:
    rsupport.test: info
    org.hibernate.type.descriptor.sql: info
