version: '3.8'

services:
##
  mysql:
    image: mysql:8.3.0
    container_name: rsupport-mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    restart: always
    environment:
      MYSQL_DATABASE: rsupport_test
      MYSQL_USER: jeon.yunki
      MYSQL_PASSWORD: 1q2w3e4r!
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
## redis
  redis:
    image: redis:alpine
    container_name: rsupport-redis
#    command: redis-server --requirepass 1q2w3e4r! --port 6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6379:6379
